#!/bin/bash

# Confirm we actually want to do this.
read -r -p "[*] Setup basic packages and configs? Y/N? " response

if [[ $response =~ ^(yes|y|Y|Yes)$ ]]; then
    systemctl enable dhcpcd
    systemctl start dhcpcd
    sleep 10s

    pacman-key --init
    pacman-key --populate
    pacman-key --refresh-keys
    pacman-key --populate
    yes '' | pacman -Syu \
        base-devel \
        rsync \
        zip unzip \
        ntp \
        openssh \
        git \
        xorg-server \
        xorg-server-utils \
        xorg-apps \
        bspwm \
        sxhkd \
        python \
        python2 \
        rxvt-unicode \
        cmake \
        gtk-engines \
        gtk-engine-aurora \
        ttf-droid \
        ttf-dejavu \
        gtk-engine-murrine \
        virtualbox-guest-modules \
        virtualbox-guest-utils

    useradd -m -g users -G vboxsf -s /bin/bash reisen

    read -r -p "[*] Setup virtualbox as a guest? Y/N? " response
    if [[ $response =~ ^(yes|y|Y|Yes)$ ]]; then
        echo -e 'vboxguest\nvboxsf\nvboxvideo' >> /etc/modules-load.d/virtualbox.conf
    fi

    systemctl enable ntpd
    systemctl start ntpd
    sudo -u reisen git clone https://github.com/Reisen/dot /home/reisen/.dot/
    sudo -u reisen make -C /home/reisen/.dot/
fi
