#!/bin/bash

# Symlink dotfiles from a dot-repo to a home location.
# Input:  Absolute Path to File/Directory
# Output: Symlink in $HOME.
# ------------------------------------------------------------------------------
target_file="${1#${PWD}}"
target_file="${target_file:1: -5}"
target_file=".${target_file}"

# Backup old dot file if it exists.
if [[ -f "$HOME/${target_file}" ]] && [[ ! -L "$HOME/${target_file}" ]]; then
    echo "  mv $HOME/${target_file} $HOME/${target_file}.old"
    mv "$HOME/${target_file}" "$HOME/${target_file}.old"
fi

# Link to the .link file in $HOME. As long as the Symlink isn't already there.
if [[ ! -L "$HOME/${target_file}" ]]; then
    echo "  ln -s ${1} $HOME/${target_file}"
    ln -s "${1}" "$HOME/${target_file}"
fi
