#!/bin/bash

function process {
    while IFS= read -r line || [[ -n $line ]]; do
        if [[ $line == *"#include"* ]]; then
            target="${line##*#include \"}"
            target="${target%%\"*}"
            process "$target"
        else
            echo -e "$line"
        fi
    done < $1
}

process "$1"
